using Caliburn.Micro;

namespace SPP_LegionV2_Management
{
	public class CharacterTableField
	{
		public string table;
		public string field;

		// Static collection of tables and fields used when deleting objects related to a character ID
		public readonly static BindableCollection<CharacterTableField> CharacterTableFields = new BindableCollection<CharacterTableField>()
		{
			new CharacterTableField() { table = "legion_characters`.`character_account_data", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_achievement", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_achievement_progress", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_action", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_adventure_quest", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_achievement", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_archaeology", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_archaeology_finds", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_army_training_info", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_artifact", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_aura", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_aura_effect", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_banned", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_battleground_data", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_battleground_random", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_achievement", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_battle_pet_journal", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_achievement", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_chat_logos", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_cheat_common", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_cuf_profiles", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_currency", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_custom_event_reapeter", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_custom_reward", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_custom_server_rewards_reapeter", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_deathmatch", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_deathmatch_store", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_declinedname", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_donate", field = "owner_guid" },

			// Disabling this until I know more
			//new CharacterTableField() { table = "legion_characters`.`character_donate_service", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_equipmentsets", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_feed_log", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison", field = "CharacterGuid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_blueprints", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_buildings", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_followers", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_missions", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_shipment", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_garrison_talents", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_gifts", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_glyphs", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_homebind", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_honor", field = "Guid" },
			new CharacterTableField() { table = "legion_characters`.`character_instance", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_inventory", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_kill", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_lfg_cooldown", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_loot_cooldown", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_pet", field = "owner" },
			new CharacterTableField() { table = "legion_characters`.`character_pet_declinedname", field = "owner" },
			new CharacterTableField() { table = "legion_characters`.`character_pvp_talent", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_daily", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_objectives", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_rewarded", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_seasonal", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_weekly", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_queststatus_world", field = "account" },
			new CharacterTableField() { table = "legion_characters`.`character_quests_ignored", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_rates", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_rename", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_reputation", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_reward", field = "owner_guid" },
			new CharacterTableField() { table = "legion_characters`.`character_share", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_skills", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_social", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_spell", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_spell_cooldown", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_stats", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_stat_kill_creature", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_talent", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_transmogs", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_transmog_outfits", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_visuals", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_visual_enchant", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`character_void_storage", field = "playerGuid" },
			new CharacterTableField() { table = "legion_characters`.`gm_tickets", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`guild", field = "leaderguid" },
			new CharacterTableField() { table = "legion_characters`.`guild_achievement", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_achievement_progress", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_bank_eventlog", field = "PlayerGuid" },
			new CharacterTableField() { table = "legion_characters`.`guild_bank_item", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_bank_right", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_bank_tab", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_challenges", field = "GuildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_eventlog", field = "PlayerGuid1" },
			new CharacterTableField() { table = "legion_characters`.`guild_eventlog", field = "PlayerGuid2" },
			new CharacterTableField() { table = "legion_characters`.`guild_finder_applicant", field = "playerGuid" },
			new CharacterTableField() { table = "legion_characters`.`guild_finder_guild_settings", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`guild_member", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`guild_newslog", field = "guildid" },
			new CharacterTableField() { table = "legion_characters`.`guild_newslog", field = "PlayerGuid" },
			new CharacterTableField() { table = "legion_characters`.`guild_rank", field = "guildId" },
			new CharacterTableField() { table = "legion_characters`.`item_instance", field = "owner_guid" },
			new CharacterTableField() { table = "legion_characters`.`item_instance_artifact", field = "char_guid" },
			new CharacterTableField() { table = "legion_characters`.`item_instance_artifact_powers", field = "char_guid" },
			new CharacterTableField() { table = "legion_characters`.`item_instance_relics", field = "char_guid" },
			new CharacterTableField() { table = "legion_characters`.`item_refund_instance", field = "player_guid" },
			new CharacterTableField() { table = "legion_characters`.`lag_reports", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`log_faction_change", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`log_rename", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`log_store_gold", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`log_store_item", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`magazine", field = "guid" },
			new CharacterTableField() { table = "legion_characters`.`mail", field = "receiver" },
			new CharacterTableField() { table = "legion_characters`.`mailbox_queue", field = "receiver_guid" },
			new CharacterTableField() { table = "legion_characters`.`mail_items", field = "receiver" },
			new CharacterTableField() { table = "legion_characters`.`petition", field = "ownerguid" },
			new CharacterTableField() { table = "legion_characters`.`petition_sign", field = "ownerguid" },
			new CharacterTableField() { table = "legion_characters`.`petition_sign", field = "playerguid" },
			new CharacterTableField() { table = "legion_characters`.`report_bugreport", field = "PlayerGuid" },
			new CharacterTableField() { table = "legion_characters`.`report_complaints", field = "ReportPlayer" }
		};
	}
}